image:
  repository: ghcr.io/attune-system/attune-docs-site
  tag: "0.1.2"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: docs.attunedev.org
      paths:
        - path: /
          pathType: Prefix
